// Mocks generated by Mockito 5.4.6 from annotations
// in chat_app/test/unit/models/chat_message_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:cloud_firestore_platform_interface/cloud_firestore_platform_interface.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDocumentReference_0<T1 extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T1> {
  _FakeDocumentReference_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSnapshotMetadata_1 extends _i1.SmartFake
    implements _i2.SnapshotMetadata {
  _FakeSnapshotMetadata_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_2 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DocumentSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentSnapshot<T extends Object?> extends _i1.Mock
    implements _i2.DocumentSnapshot<T> {
  MockDocumentSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i3.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i2.DocumentReference<T> get reference =>
      (super.noSuchMethod(
            Invocation.getter(#reference),
            returnValue: _FakeDocumentReference_0<T>(
              this,
              Invocation.getter(#reference),
            ),
          )
          as _i2.DocumentReference<T>);

  @override
  _i2.SnapshotMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeSnapshotMetadata_1(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i2.SnapshotMetadata);

  @override
  bool get exists =>
      (super.noSuchMethod(Invocation.getter(#exists), returnValue: false)
          as bool);

  @override
  dynamic get(Object? field) =>
      super.noSuchMethod(Invocation.method(#get, [field]));

  @override
  dynamic operator [](Object? field) =>
      super.noSuchMethod(Invocation.method(#[], [field]));
}

/// A class which mocks [Timestamp].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimestamp extends _i1.Mock implements _i4.Timestamp {
  MockTimestamp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get seconds =>
      (super.noSuchMethod(Invocation.getter(#seconds), returnValue: 0) as int);

  @override
  int get nanoseconds =>
      (super.noSuchMethod(Invocation.getter(#nanoseconds), returnValue: 0)
          as int);

  @override
  int get millisecondsSinceEpoch =>
      (super.noSuchMethod(
            Invocation.getter(#millisecondsSinceEpoch),
            returnValue: 0,
          )
          as int);

  @override
  int get microsecondsSinceEpoch =>
      (super.noSuchMethod(
            Invocation.getter(#microsecondsSinceEpoch),
            returnValue: 0,
          )
          as int);

  @override
  DateTime toDate() =>
      (super.noSuchMethod(
            Invocation.method(#toDate, []),
            returnValue: _FakeDateTime_2(this, Invocation.method(#toDate, [])),
          )
          as DateTime);

  @override
  int compareTo(_i4.Timestamp? other) =>
      (super.noSuchMethod(
            Invocation.method(#compareTo, [other]),
            returnValue: 0,
          )
          as int);
}
